name: WordCard
description: So'zlarni yodlash uchun saqla, esdan chiqarish uchunmas
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.9.1 
  go_router: ^14.1.0    
  flutter_animate: ^4.5.0
  google_fonts: ^6.3.0
  flutter_dotenv: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true